---
- hosts: test-server
  become: true
  tasks:
  - name: update
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install docker.io -y

  - name: stop the docker container 
    command: docker stop health

  - name: remove the docker container
    command: docker rm  health
  - name: docker run 
    command: docker run -itd -p 8081:8082 --name health rakesh1299/health:1.0 
