apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deployment
  namespace: prod
  labels:
    app: health
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
      - name: health
        image: rakesh1299/health:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: prod-service
  namespace: prod
spec:
  selector:
    app: prod
  type: NodePort
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    protocol: TCP
    nodePort: 30200
